title: SolrPyProxy
description: A FastAPI-based specialized proxy that connect to SolR instace to provide a safer way to perform advanced metadata queries
version: 0.1.0
contact:
  name: Person Name
  email: examplel@example.com