# Basic FastAPI configuration
title: SolrPyProxy
description: A FastAPI-based specialized proxy that connect to SolR instace to provide a safer way to perform advanced metadata queries
version: 0.1.0
contact:
  name: Person Name
  email: examplel@example.com

# Routes configuration
routes:
  - path: /health
    method: GET
    description: Check the health of the Solr instance
    tags:
      - example
    handler: health
    response_model: SimpleMessage
    request:
      message: OK

# Metadata mapping configuration for Solr
metadata_mapping:
  MappedSolrModel:
    dc.title:
      name: title
      type: str
      required: false
    dc.date.issued:
      name: date_issued
      type: datetime
      required: true